// javascript program for rolling dices

function RollingDices(){

    const NumberOfDiceRoll = document.getElementById("NumberOfDiceRoll").value;
    const outputresult = document.getElementById("outputresult");
    const imageDice = document.getElementById("imageDice");

    // create array for values that will be generated by our math.random function
    const values = [];
    const images = [];

   // for loop to iterate according number dices specified

    for (let i = 0; i < NumberOfDiceRoll ; i ++){

        const generatedvalues = Math.floor(Math.random() * 6) + 1;
        
        values.push(generatedvalues);
        images.push(`<img src = "/photos/${generatedvalues}.jpg" height ="200" width = "200" alt ="Dice ${generatedvalues}">`);

    }
    outputresult.textContent = `Dice Result:${values.join(", ")}`;
    imageDice.innerHTML = images.join(' ');
}